# This file was automatically generated by SWIG
package sendOSC;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package sendOSC;
bootstrap sendOSC;
var_sendOSC_init();
package sendOSC;
@EXPORT = qw( );
1;
